# job.yml
parameters:
  jobs: []

jobs:
- ${{ each job in parameters.jobs }}: # Then do each job
  - ${{ each pair in job }}:          # Insert all properties other than "dependsOn"
      ${{ if ne(pair.key, 'dependsOn') }}:
        ${{ pair.key }}: ${{ pair.value }}
    dependsOn:                        # Inject dependency
    - ${{ if job.dependsOn }}:
      - ${{ job.dependsOn }}