resources:
- repo: self
jobs:
- job: Job_1
  displayName: Security
  condition: succeeded()
  pool:
    name: Hosted VS2017
  steps:
  - template: _securityChecks.yml

- job: Job_2
  displayName: Build and Sign Oryx Binaries
  condition: succeeded()
  pool:
    name: VSEng-MicroBuildVS2017
    demands:
    - msbuild
    - visualstudio
  variables:
    SignType: 'test'
  steps:
  - template: _signbinary.yml

- job: Job_BuildImage
  displayName: Build and Test Build Image
  dependsOn: Job_2
  condition: succeeded()
  pool:
    name: OryxLinux
  steps:
  - task: DownloadPipelineArtifact@0
    displayName: 'Download Pipeline Artifact'
    inputs:
      pipelineId: 'Oryx-CI'
      artifactName: 'drop-$(Build.BuildNumber)'
      targetPath: '$(Build.SourcesDirectory)'
    condition: >
     and(eq(variables['Build.DefinitionName'], 'Oryx-CI'), in(variables['Build.Reason'], 'Schedule', 'Manual'),
     or(startsWith(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'],'refs/heads/patch/' )))

  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]true"
      echo "##vso[task.setvariable variable=TestBuildImages;]true"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushBuildImages;]true"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]true"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_RuntimeImages
  displayName: Build and Test Runtime Images
  condition: succeeded()
  pool:
    name: OryxLinux
  # Building runtime images can take a long time due our PHP images
  timeoutInMinutes: 150
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]true"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_PythonIntegrationTests
  displayName: Run Python Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  timeoutInMinutes: 150
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=python"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]true"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_DotNetCoreIntegrationTests
  displayName: Run DotNetCore Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=dotnetcore"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]true"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_NodeIntegrationTests
  displayName: Run NodeJs Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  timeoutInMinutes: 150
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=node"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]true"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_PhpIntegrationTests
  displayName: Run Php Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=php"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]true"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_DbIntegrationTests
  displayName: Run Database Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=db"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]true"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_ENDIntegrationTests
  displayName: End of Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
    - Job_PythonIntegrationTests
    - Job_PhpIntegrationTests
    - Job_NodeIntegrationTests
    - Job_DotNetCoreIntegrationTests
    - Job_DbIntegrationTests
  pool:
    name: OryxLinux
  steps:
  - task: ms-devlabs.utilitytasks.task-Shellpp.Shell++@0
    displayName: 'End of Integration Tests'
    inputs:
      type: InlineScript
      script: 'echo "Integration tests ended"'
trigger: none