resources:
- repo: self
jobs:
- job: Job_SecurityCheck
  displayName: Security
  condition: succeeded()
  pool:
    name: Hosted VS2017
  steps:
  - template: _securityChecks.yml

- job: Job_SignBinaries
  displayName: Build and Sign Oryx Binaries
  condition: succeeded()
  pool:
    name: VSEng-MicroBuildVS2017
    demands:
    - msbuild
    - visualstudio
  variables:
    SignType: 'test'
  steps:
  - template: _signbinary.yml

- template: _integration.yml
  parameters:
      isCIBuild: 'true'
  dependsOn: Job_SignBinaries  

trigger: none