resources:
- repo: self
jobs:
- job: Job_Security
  displayName: Security
  condition: succeeded()
  pool:
    name: Hosted VS2017
  steps:
  - template: _securityChecks.yml

- job: Job_SignBinaries
  displayName: Build and Sign Oryx Binaries
  pool:
    name: VSEng-MicroBuildVS2017
    demands:
    - msbuild
    - visualstudio
  variables:
    SignType: 'test'
  steps:
  - template: _signbinary.yml

- job: Job_BuildImage
  displayName: Build and Test Build Image
  dependsOn: Job_SignBinaries
  condition: succeeded()
  pool:
    name: OryxLinux
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]true"
      echo "##vso[task.setvariable variable=TestBuildImages;]true"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushBuildImages;]true"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: _buildParallel.yml
    parameters:
      pushToDockerHub: 'true'

- template: _integration.yml
  parameters:
      isCIBuild: 'true'

trigger: none