resources:
- repo: self
  fetchDepth: 15
jobs:
- job: Job_Security
  displayName: Security
  condition: succeeded()
  pool:
    name: Hosted VS2017
  steps:
  - template: _securityChecks.yml

- template: _integration.yml
  parameters:
      isCIBuild: 'false'