resources:
- repo: self
  fetchDepth: 15
jobs:
- job: Job_Security
  displayName: Security
  condition: succeeded()
  pool:
    name: Hosted VS2017
  steps:
  - template: _securityChecks.yml

- job: Job_BuildImage
  displayName: Build and Test Build Image
  pool:
    name: OryxLinux
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]true"
      echo "##vso[task.setvariable variable=TestBuildImages;]true"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushBuildImages;]true"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: _buildParallel.yml
    parameters:
      pushToDockerHub: 'false'

- template: _integration.yml
  parameters:
      isCIBuild: 'false'

trigger: none