resources:
- repo: self
  fetchDepth: 15
jobs:
- job: Job_Security
  displayName: Security
  pool:
    name: Hosted VS2017
  steps:
  - template: _securityChecks.yml

- job: Job_BuildImage
  displayName: Build and Test Build Image
  pool:
    name: OryxLinux
  timeoutInMinutes: 45
  steps:
  - script: |
      echo "##vso[task.setvariable variable=ImageFilter;]build"
      echo "##vso[task.setvariable variable=Enabled;]true"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: _buildtestandpushimage.yml

- job: Job_NodeRuntimeImages
  displayName: Build and Test Node Runtime Images
  pool:
    name: OryxLinux
  timeoutInMinutes: 45
  steps:
  - script: |
      echo "##vso[task.setvariable variable=ImageFilter;]node"
      echo "##vso[task.setvariable variable=Enabled;]true"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: _buildtestandpushimage.yml

- job: Job_PythonRuntimeImages
  displayName: Build and Test Python Runtime Images
  pool:
    name: OryxLinux
  timeoutInMinutes: 45
  steps:
  - script: |
      echo "##vso[task.setvariable variable=ImageFilter;]python"
      echo "##vso[task.setvariable variable=Enabled;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: _buildtestandpushimage.yml  

trigger: none
